### PR TITLE
add linting options

### PR DESCRIPTION
**Pull request by bircni**
I enabled some lints in clippy to improve the style of the code.
There are some todos open with missing panic docs.
It is not that good to use unwraps as we don't want to crash the users experience, maybe instead use the crate `anyhow` to safely handle errors.

### CODE REVIEW

**Review by blitzarx1 — COMMENTED** [review]
Thanks for such thorough work.

About using unwraps - totally agree. But I think we will come to this after the Layout feature is delivered and we start to stabilize APIs approaching to stable release. I will consider `anyhow` for sure.

What do you think about enhancing linter in the .github/workflows `linter` step?

**Comment by bircni** [comment]
now also enhanced the workflow

**Comment by bircni** [comment]
still working on another suggestion - maybe I can finish that later on!

**Comment by bircni** [comment]
@blitzarx1 I started adding anyhow - maybe you could have a look at it?

**Comment by blitzarx1** [comment]
lets extract `anyhow` changes to separate PR.

Also I am not sure this is the right time to add anyhow usage, while I am mid adding Layout feature. Let us return to anyhow after the Layout. When we will be on stabilization track. 

I am ready to continue wiht this PR, but without anyhow changes.

**Comment by bircni** [comment]
was just a check gonna revert them and finish the pr to make it ready for review finally!

**Review by blitzarx1 — APPROVED** [review]
Good begining for the stabilization track

**Pull request merged**
