### PR TITLE
export EdgeShapeBuilder and TipProps

### LINKED ISSUE #203: add public exports required to implement DisplayEdge
The DefaultDisplayEdge uses the two structs `EdgeShapeBuilder` and `TipProps` for drawing the edges.

When implementing a custom struct implementing the `DisplayEdge` trait from outside the crate, the two structs are not visible, even though they are declared public. The reason is that they are not publicly exported in the corresponding mod.rs and lib.rs files.

If requested, I could set up a pull request (once I figured out how to do this...), as I have fixed the problem in my local git repository.

### PR DESCRIPTION
**Pull request by nacl42**
fixes #203

### CODE REVIEW

**Comment by blitzarx1** [comment]
As I said in the #203 I do not see the reason to export these structs.

**Comment by nacl42** [comment]
I am not sure if I describe my problem properly, so I will try again. 

The situation is as follows: I am building a graph with a custom implementation of the `DisplayEdge` trait, i.e. I would like to have my own customized edge drawing. For this, I need to implement the two functions `shapes`, `update` and `is_inside`. In your original source code, i.e. in `src/draw/displays_default/edge.rs`, the shapes for the `DefaultEdgeShape` are constructed using an `EdgeShapeBuilder`.  Therefore I tried to duplicate your code as a starting point for my own experimental `CustomEdgeShape`.  But then I hit the restriction that `EdgeShapeBuilder` is private outside the `egui_graphs` crate. Similar problem with `TipProps`.

So from my understanding, your API exposes enough for the _user_ of the library, but not for someone who would like to re-implement the edge drawing or the node drawing.

I hope I was able to convey my problem. If you have another solution or if I have overlooked something obvious, I would be happy about any hint.

**Comment by blitzarx1** [comment]
@nacl42 hope this will help
https://github.com/blitzarx1/egui_graphs/tree/master/examples/rainbow_edges

**Comment by nacl42** [comment]
@blitzarx1 Thank you so much for the rainbow example. It is both illustrative and beautiful. This solves my problem in a much better way!

**Comment by blitzarx1** [comment]
Nice! Glad to hear it!

**Pull request closed without merging**
