### PR TITLE
[Feature] Ability to set/change data after node creation

### PR DESCRIPTION
**Pull request by TDiblik**
I've hit this roadblock sooo many times. I try to update the underlying data, but I am unable to, because the library only returns read-only ref to current data. At the moment, only option to overcome this problem is to re-generate the node. This commit fixes that by adding methods (mutable and immutable) for changing the underlying data.

### CODE REVIEW

**Comment by TDiblik** [comment]
Also added the ability to set edge width, since that's also something that could be useful (especially when there is large number of nodes, the thick lines are a huge distraction) :D

**Comment by blitzarx1** [comment]
Thanks! Nice, that you highlighted these things. They are needed 100%. I just did not have such cases myself and I grateful that you are using the lib and find these childhood problems)

**Comment by blitzarx1** [comment]
I ll merge in couple of hours and release a new version with these changes, for them not longer being a blocker in your project

**Comment by TDiblik** [comment]
Hey, np, thanks for merging <3! 

Btw, don't feel pressured to release new versions, I'm usually working on the project, find something that could be added to the lib, fork it, add it as a feature, instruct cargo to use the fork (also testing the changes that way) and then wait for a new release :D -- tldr; I don't mind waiting, since I can use the fork until you want to make a new release

**Comment by blitzarx1** [comment]
No problem because it is not a breaking change. Minor versions for me are easy to release

**Pull request merged**
