### PR TITLE
Added serialization attr for default stuff and some constructor helpers when creating nodes

### PR DESCRIPTION
**Pull request by patrik-cihal**

### CODE REVIEW

**Comment by patrik-cihal** [comment]
Actually with_location doesn't make much sense if I need to bind it first... I'll remove it..

**Comment by blitzarx1** [comment]
Good point. These api is in refactor now. I am not sure about bind approach either.

**Comment by patrik-cihal** [comment]
Yeah what is it for?

**Review by blitzarx1 — APPROVED** [review]

**Comment by patrik-cihal** [comment]
Does the node need to know its own index?

**Comment by blitzarx1** [comment]
It helps to simplify many internal processes. For node this is not much beneficial, bot for edge it is very beneficial. Because for drawing we use order of and edge to bend it accordingly. And to compute order we need always to be aware of edges endpoints and compute their order on every frame - for that we would need to pass graph reference inside drawing context, which would make generic system even more complicated.

But I think I will rethink this approach soon, now when we have more or less stable implementation of `NodeDisplay` and `EdgeDisplay` trait, I think I can find a way to optimize it and keep only `order` prop inside of edge and recompute it only if graph is changed (edge/node added or deleted)

**Comment by patrik-cihal** [comment]
Yes it is so hard to even add a node. Perhaps I'm doing something wrong...
```rust
let mut new_node = Node::new(NodeData{ content: "".into() } );
                    new_node.set_location(Pos2::new(new_pos.x, new_pos.y));
                    self.gc.write().unwrap().g.add_node(new_node);
```
And it hasn't even been binded now.

**Comment by blitzarx1** [comment]
Yep, I will think about some macros or further refactorings. But I think this case can be covered with `transform::add_node` or `transform::add_node_custom`

**Comment by patrik-cihal** [comment]
I would simply avoid unbinded nodes altogether. If something is unbinded it can be represted just as NodeData.

**Comment by patrik-cihal** [comment]
Oh nvm that's prob not possible.

**Comment by blitzarx1** [comment]
I will definitely prioritize usability before coming stable.

**Comment by patrik-cihal** [comment]
What do you mean by that? Do you think unbinded nodes are necessary?

**Comment by blitzarx1** [comment]
#135  Added our concerns hers.

No I just agree that usability is becoming an issue, and I need to work in this direction before releasing stable versions. If you would have any proposals in this regard, we can move the discussion to #135 

About binding nodes I am almost sure that this can be avoided and just have one-step process for creating, modifying or deleting node.

**Pull request merged**
